$ErrorActionPreference = "Stop"

$EnvFile = ".env.prod"
$ComposeFile = "docker-compose.prod.yml"

Write-Host "Migo - Self-Hosted Setup" -ForegroundColor Cyan
Write-Host "========================"
Write-Host

# Check for docker
try { docker --version | Out-Null } catch {
    Write-Host "Error: Docker is not installed. Install it from https://docs.docker.com/desktop/install/windows/" -ForegroundColor Red
    exit 1
}

# Check for docker compose
try { docker compose version | Out-Null } catch {
    Write-Host "Error: Docker Compose is not available." -ForegroundColor Red
    exit 1
}

# Don't overwrite existing env file
if (Test-Path $EnvFile) {
    Write-Host "Found existing $EnvFile - skipping generation."
    Write-Host "Delete it and re-run this script to regenerate."
    Write-Host
} else {
    # Detect public IP (use APIs that always return plain text)
    Write-Host "Detecting public IP..."
    $PublicIP = $null
    try { $PublicIP = (Invoke-RestMethod -Uri "https://api.ipify.org" -TimeoutSec 5).Trim() } catch {}
    if (-not $PublicIP) {
        try { $PublicIP = (Invoke-RestMethod -Uri "https://icanhazip.com" -TimeoutSec 5).Trim() } catch {}
    }

    if (-not $PublicIP) {
        $PublicIP = Read-Host "Could not detect public IP. Enter your server's public IP"
    } else {
        Write-Host "Detected: $PublicIP"
        $confirm = Read-Host "Use this IP? (Y/n)"
        if ($confirm -match "^[Nn]") {
            $PublicIP = Read-Host "Enter your server's public IP"
        }
    }

    # Generate secrets using .NET RNG (works on both .NET Framework and .NET 6+)
    $rng = [System.Security.Cryptography.RNGCryptoServiceProvider]::new()

    function New-Secret {
        $bytes = New-Object byte[] 32
        $rng.GetBytes($bytes)
        return ($bytes | ForEach-Object { $_.ToString("x2") }) -join ""
    }

    function New-ShortSecret {
        $bytes = New-Object byte[] 4
        $rng.GetBytes($bytes)
        return ($bytes | ForEach-Object { $_.ToString("x2") }) -join ""
    }

    $PostgresPassword = New-Secret
    $JwtAccessSecret = New-Secret
    $JwtRefreshSecret = New-Secret
    $LivekitApiKey = "migo$(New-ShortSecret)"
    $LivekitApiSecret = New-Secret

    # Write env file
    $date = (Get-Date).ToUniversalTime().ToString("yyyy-MM-dd")
    @"
# Generated by setup.ps1 on $date

# PostgreSQL
POSTGRES_USER=migo
POSTGRES_PASSWORD=$PostgresPassword
POSTGRES_DB=migo

# JWT secrets
JWT_ACCESS_SECRET=$JwtAccessSecret
JWT_REFRESH_SECRET=$JwtRefreshSecret

# LiveKit
LIVEKIT_API_KEY=$LivekitApiKey
LIVEKIT_API_SECRET=$LivekitApiSecret
LIVEKIT_PUBLIC_URL=ws://${PublicIP}:7880

# mediasoup (screen sharing)
MEDIASOUP_ANNOUNCED_IP=$PublicIP
"@ | Set-Content -Path $EnvFile -NoNewline

    Write-Host
    Write-Host "Created $EnvFile with generated secrets." -ForegroundColor Green
}

Write-Host
Write-Host "Required ports (open these on your firewall):" -ForegroundColor Yellow
Write-Host "  8080        TCP      - Migo API + WebSocket"
Write-Host "  7880-7881   TCP      - LiveKit signaling"
Write-Host "  40000-40100 TCP+UDP  - Screen sharing (mediasoup)"
Write-Host "  50000-50100 UDP      - Voice (LiveKit WebRTC)"
Write-Host

$start = Read-Host "Start Migo now? (Y/n)"
if ($start -match "^[Nn]") {
    Write-Host
    Write-Host "Run manually with:"
    Write-Host "  docker compose -f $ComposeFile --env-file $EnvFile up -d"
    exit 0
}

Write-Host
Write-Host "Starting Migo..."
docker compose -f $ComposeFile --env-file $EnvFile up -d

Write-Host
Write-Host "Migo is running! Connect with:" -ForegroundColor Green
Write-Host "  Add Workspace -> http://${PublicIP}:8080"
