#!/usr/bin/env bash
set -euo pipefail

ENV_FILE=".env.prod"
COMPOSE_FILE="docker-compose.prod.yml"

echo "Migo — Self-Hosted Setup"
echo "========================"
echo

# Check for docker
if ! command -v docker &>/dev/null; then
  echo "Error: Docker is not installed. Install it from https://docs.docker.com/engine/install/"
  exit 1
fi

# Check for docker compose
if ! docker compose version &>/dev/null; then
  echo "Error: Docker Compose is not installed. Install it from https://docs.docker.com/compose/install/"
  exit 1
fi

# Don't overwrite existing env file
if [ -f "$ENV_FILE" ]; then
  echo "Found existing $ENV_FILE — skipping generation."
  echo "Delete it and re-run this script to regenerate."
  echo
else
  # Detect public IP
  echo "Detecting public IP..."
  PUBLIC_IP=$(curl -s --max-time 5 https://api.ipify.org || curl -s --max-time 5 https://icanhazip.com || true)

  if [ -z "$PUBLIC_IP" ]; then
    echo "Could not detect public IP automatically."
    read -rp "Enter your server's public IP: " PUBLIC_IP
  else
    echo "Detected: $PUBLIC_IP"
    read -rp "Use this IP? (Y/n): " confirm
    if [[ "$confirm" =~ ^[Nn] ]]; then
      read -rp "Enter your server's public IP: " PUBLIC_IP
    fi
  fi

  # Generate secrets
  gen_secret() { openssl rand -hex 32; }

  POSTGRES_PASSWORD=$(gen_secret)
  JWT_ACCESS_SECRET=$(gen_secret)
  JWT_REFRESH_SECRET=$(gen_secret)
  LIVEKIT_API_KEY="migo$(openssl rand -hex 4)"
  LIVEKIT_API_SECRET=$(gen_secret)

  # Write env file
  cat > "$ENV_FILE" <<EOF
# Generated by setup.sh on $(date -u +"%Y-%m-%d")

# PostgreSQL
POSTGRES_USER=migo
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=migo

# JWT secrets
JWT_ACCESS_SECRET=$JWT_ACCESS_SECRET
JWT_REFRESH_SECRET=$JWT_REFRESH_SECRET

# LiveKit
LIVEKIT_API_KEY=$LIVEKIT_API_KEY
LIVEKIT_API_SECRET=$LIVEKIT_API_SECRET
LIVEKIT_PUBLIC_URL=ws://$PUBLIC_IP:7880

# mediasoup (screen sharing)
MEDIASOUP_ANNOUNCED_IP=$PUBLIC_IP
EOF

  echo
  echo "Created $ENV_FILE with generated secrets."
fi

echo
echo "Required ports (open these on your firewall):"
echo "  8080        TCP   — Migo API + WebSocket"
echo "  7880-7881   TCP   — LiveKit signaling"
echo "  40000-40100 TCP+UDP — Screen sharing (mediasoup)"
echo "  50000-50100 UDP   — Voice (LiveKit WebRTC)"
echo

read -rp "Start Migo now? (Y/n): " start
if [[ "$start" =~ ^[Nn] ]]; then
  echo
  echo "Run manually with:"
  echo "  docker compose -f $COMPOSE_FILE --env-file $ENV_FILE up -d"
  exit 0
fi

echo
echo "Starting Migo..."
docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" up -d

echo
echo "Migo is running! Connect with:"
echo "  Add Workspace → http://$PUBLIC_IP:8080"
