/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function forceKeyframe(): void

export declare function isScreenShareRunning(): boolean

export interface JsDisplayInfo {
  index: number
  name: string
  width: number
  height: number
}

export interface JsEngineStats {
  fps: number
  encodeMs: number
  bitrateMbps: number
  framesEncoded: number
  bytesSent: number
}

export interface JsScreenShareConfig {
  /** LiveKit server URL (e.g., "ws://localhost:7880"). */
  serverUrl: string
  /** LiveKit access token. */
  token: string
  /** Capture target type: "primary", "display", or "window". */
  targetType: string
  /** Display index (for target_type "display") or window handle (for "window"). */
  targetId?: number
  /** Target FPS. */
  fps: number
  /** Target bitrate in bits/sec. */
  bitrate: number
  /** Whether to show cursor in capture. */
  showCursor: boolean
  /** Whether to capture system audio. */
  captureAudio: boolean
  /** Audio mode: "system" or process PID (number as string). */
  audioMode?: string
}

export interface JsWindowInfo {
  handle: number
  title: string
  processName: string
}

export declare function listDisplays(): Array<JsDisplayInfo>

export declare function listWindows(): Array<JsWindowInfo>

export declare function startScreenShare(config: JsScreenShareConfig, onError: ((err: Error | null, arg: string) => any), onStopped: ((err: Error | null, ) => any), onStats: ((err: Error | null, arg: JsEngineStats) => any)): Promise<void>

export declare function stopScreenShare(): void

export declare function version(): string
